#!/bin/bash
# ============================================================================
# ONE2LVOS QUICK START DEPLOYMENT SCRIPT
# ============================================================================
# This script will:
# 1. Clone the One2lvOS repository
# 2. Create .env with all API keys configured
# 3. Deploy all services with Docker Compose
# 4. Initialize Astra DB collections
# 5. Show access information
# ============================================================================

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
NC='\033[0m' # No Color

# Banner
clear
echo -e "${CYAN}"
cat << "EOF"
╔══════════════════════════════════════════════════════════════╗
║                                                              ║
║                    ONE2LVOS QUICKSTART                       ║
║              Production Deployment Installer                 ║
║                                                              ║
║                         v1.0.2                               ║
║                                                              ║
╚══════════════════════════════════════════════════════════════╝
EOF
echo -e "${NC}"

# Functions
log_info() {
    echo -e "${CYAN}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[✓]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[!]${NC} $1"
}

log_error() {
    echo -e "${RED}[✗]${NC} $1"
}

log_step() {
    echo ""
    echo -e "${MAGENTA}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${MAGENTA}  $1${NC}"
    echo -e "${MAGENTA}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
}

# Check if Docker is installed
check_docker() {
    if ! command -v docker &> /dev/null; then
        log_error "Docker is not installed!"
        log_info "Please install Docker first: https://docs.docker.com/get-docker/"
        exit 1
    fi
    log_success "Docker is installed"
}

# Check if Docker Compose is installed
check_docker_compose() {
    if ! command -v docker compose &> /dev/null; then
        log_error "Docker Compose is not installed!"
        log_info "Please install Docker Compose v2+: https://docs.docker.com/compose/install/"
        exit 1
    fi
    log_success "Docker Compose is installed"
}

# Get installation directory
get_install_dir() {
    INSTALL_DIR="${1:-$HOME/one2lvos}"
    log_info "Installation directory: $INSTALL_DIR"

    if [ -d "$INSTALL_DIR" ]; then
        log_warning "Directory $INSTALL_DIR already exists"
        read -p "Do you want to remove it and reinstall? (y/N): " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            log_info "Removing existing directory..."
            rm -rf "$INSTALL_DIR"
        else
            log_error "Installation cancelled"
            exit 1
        fi
    fi
}

# Clone repository
clone_repo() {
    log_step "STEP 1: Cloning One2lvOS Repository"

    log_info "Cloning from GitHub..."
    git clone https://github.com/one2lv-com/One2lvos.git "$INSTALL_DIR"

    cd "$INSTALL_DIR"
    log_success "Repository cloned to $INSTALL_DIR"
}

# Create .env file
create_env() {
    log_step "STEP 2: Creating Production Environment Configuration"

    log_info "Generating .env file with all API keys..."

    cat > .env << 'EOF'
# ============================================================================
# ONE2LVOS PRODUCTION ENVIRONMENT CONFIGURATION
# ============================================================================
# Auto-generated by quickstart script
# Deploy Date: 2026-09-08
# Version: 1.0.2-production

# ============================================================================
# ASTRA DB VECTOR MEMORY (DataStax) - NVIDIA Vectorize Integration
# ============================================================================
ASTRA_DB_API_ENDPOINT=https://9b5b1939-fd21-477d-95b8-a1aecc5f90b9-us-east-2.apps.astra.datastax.com
ASTRA_DB_APPLICATION_TOKEN=AstraCS:YOUR_TOKEN_HERE
ASTRA_DB_KEYSPACE=sovereign_memory

# NVIDIA Embedding Provider (Managed by Astra - No API key needed for hosted integration)
# Model: nvidia/nv-embedqa-e5-v5 (1024 dimensions, optimized for Q&A)
ASTRA_NVIDIA_MODEL=nvidia/nv-embedqa-e5-v5
ASTRA_VECTOR_METRIC=cosine

# ============================================================================
# SUPABASE CONFIGURATION (Backup/Sync)
# ============================================================================
SUPABASE_URL=https://pplbxjguhmfeuptyamic.supabase.co
SUPABASE_ANON_KEY=YOUR_SUPABASE_ANON_KEY
SUPABASE_SERVICE_KEY=YOUR_SUPABASE_SERVICE_KEY
DATABASE_URL=postgresql://postgres.pplbxjguhmfeuptyamic:[YOUR-PASSWORD]@aws-0-us-west-1.pooler.supabase.com:6543/postgres

# ============================================================================
# SERVER CONFIGURATION
# ============================================================================
PORT=8787
NODE_PORT=8787
PYTHON_PORT=3002
NGINX_PORT=80
NODE_ENV=production

# ============================================================================
# NVIDIA AI API KEYS (Multiple models/endpoints)
# ============================================================================
# Primary Nemotron Super (70B instruct)
NVIDIA_API_KEY=nvapi-YOUR_PRIMARY_KEY

# Secondary Llama-3.1 Nemotron 70B
NVIDIA_API_KEY_SECONDARY=nvapi-YOUR_SECONDARY_KEY

# Nemotron Super (Step-1 405B)
NVIDIA_API_KEY_NEMOTRON_SUPER=nvapi-YOUR_NEMOTRON_KEY

# MiniMax (Abab-6.5)
NVIDIA_API_KEY_MINIMAX=nvapi-YOUR_MINIMAX_KEY

# StepFun (Step-2 16K)
NVIDIA_API_KEY_STEPFUN=nvapi-YOUR_STEPFUN_KEY

# Kimi (Moonshot-v1-128K)
NVIDIA_API_KEY_KIMI=nvapi-YOUR_KIMI_KEY

# NVIDIA API Endpoint (OpenAI Compatible)
NVIDIA_API_ENDPOINT=https://integrate.api.nvidia.com/v1

# ============================================================================
# GEMINI AI (Google Generative AI)
# ============================================================================
GEMINI_API_KEY=YOUR_GEMINI_KEY
GEMINI_CLIENT_ID=gen-lang-client-0273258333
GEMINI_AGENT_NAME=Astra
GEMINI_MODEL=gemini-pro
GEMINI_ENDPOINT=https://generativelanguage.googleapis.com/v1beta

# ============================================================================
# MATON API (Task Automation)
# ============================================================================
MATON_API_KEY=YOUR_MATON_KEY

# ============================================================================
# STEAM WEB API (Lumenis Gaming Integration)
# ============================================================================
STEAM_API_KEY=YOUR_STEAM_KEY
STEAM_DOMAIN=https://github.com/one2lv-com/Lumenis.io

# ============================================================================
# PYTHON BACKEND (FastAPI Sovereign Council)
# ============================================================================
PYTHON_API_URL=http://one2lvos-python:3002
PYTHON_HOST=0.0.0.0

# ============================================================================
# NODE FRONTEND (AI Lobby)
# ============================================================================
NODE_API_URL=http://one2lvos-node:8787
NODE_HOST=0.0.0.0

# ============================================================================
# CORS & SECURITY
# ============================================================================
ALLOWED_ORIGINS=http://localhost,http://localhost:80,http://localhost:8787,http://localhost:3002
CORS_ENABLED=true

# ============================================================================
# ONE2LVOS SYSTEM
# ============================================================================
O2PNG_VERSION=1.0
SNAPSHOT_AUTO_SAVE=true
SNAPSHOT_INTERVAL=300000
RECOVERY_MODE=transactional
BOOT_TIMEOUT=30000

# ============================================================================
# LOGGING & MONITORING
# ============================================================================
LOG_LEVEL=info
LOG_FORMAT=json
ENABLE_METRICS=true
METRICS_PORT=9090

# ============================================================================
# DOCKER COMPOSE SERVICES
# ============================================================================
COMPOSE_PROJECT_NAME=one2lvos
RESTART_POLICY=unless-stopped

# ============================================================================
# END OF CONFIGURATION
# ============================================================================
EOF

    log_success ".env file created with all API keys configured"
}

# Deploy services
deploy_services() {
    log_step "STEP 3: Deploying One2lvOS Services"

    log_info "Starting Docker Compose deployment..."
    chmod +x deploy.sh

    log_info "Pulling Docker images..."
    docker compose -f docker-compose.production.yml pull || log_warning "Some images need to be built locally"

    log_info "Building Docker images..."
    docker compose -f docker-compose.production.yml build

    log_info "Starting all services..."
    docker compose -f docker-compose.production.yml up -d

    log_success "Services started"

    log_info "Waiting for services to stabilize (15 seconds)..."
    sleep 15
}

# Initialize Astra DB
init_astra() {
    log_step "STEP 4: Initializing Astra DB Collections"

    log_info "Setting up NVIDIA vectorize collections..."

    # Run the astra-init container
    docker compose -f docker-compose.production.yml run --rm astra-init || {
        log_warning "Astra DB initialization may have failed, but continuing..."
    }

    log_success "Astra DB initialized"
}

# Check service health
check_health() {
    log_step "STEP 5: Verifying Service Health"

    sleep 5

    # Check Nginx
    log_info "Checking Nginx Gateway..."
    if curl -f -s http://localhost:80/health > /dev/null 2>&1; then
        log_success "✓ Nginx Gateway: Healthy"
    else
        log_warning "✗ Nginx Gateway: Not responding yet (may need more time)"
    fi

    # Check Node AI Lobby
    log_info "Checking Node AI Lobby..."
    if curl -f -s http://localhost:8787/health > /dev/null 2>&1; then
        log_success "✓ Node AI Lobby: Healthy"
    else
        log_warning "✗ Node AI Lobby: Not responding yet (may need more time)"
    fi

    # Check Python Core
    log_info "Checking Python Core..."
    if curl -f -s http://localhost:3002/health > /dev/null 2>&1; then
        log_success "✓ Python Core: Healthy"
    else
        log_warning "✗ Python Core: Not responding yet (may need more time)"
    fi
}

# Show access information
show_access() {
    log_step "🎉 DEPLOYMENT COMPLETE!"

    SERVER_IP=$(hostname -I | awk '{print $1}')

    echo -e "${GREEN}"
    cat << "EOF"
╔══════════════════════════════════════════════════════════════╗
║                                                              ║
║              ONE2LVOS IS ONLINE AND READY!                   ║
║                                                              ║
╚══════════════════════════════════════════════════════════════╝
EOF
    echo -e "${NC}"

    echo -e "${CYAN}📍 Installation Directory:${NC}"
    echo -e "   ${INSTALL_DIR}"
    echo ""

    echo -e "${CYAN}🌐 Access Points:${NC}"
    echo ""
    echo -e "${GREEN}Main Applications:${NC}"
    echo -e "   🏠 Main UI:          http://${SERVER_IP}/"
    echo -e "   🌌 Infinity Glasses: http://${SERVER_IP}/Infinity_Glasses/"
    echo -e "   💻 Aetherix:         http://${SERVER_IP}/Aetherix/"
    echo -e "   🎮 Lumenis:          http://${SERVER_IP}/Lumenis/"
    echo -e "   🤖 AI Lobby:         http://${SERVER_IP}/Agentic_Control/"
    echo ""
    echo -e "${GREEN}API Endpoints:${NC}"
    echo -e "   📡 Node API:         http://${SERVER_IP}:8787"
    echo -e "   🐍 Python API:       http://${SERVER_IP}:3002"
    echo ""
    echo -e "${GREEN}Health Checks:${NC}"
    echo -e "   ✓ Nginx:             http://${SERVER_IP}/health"
    echo -e "   ✓ Node:              http://${SERVER_IP}:8787/health"
    echo -e "   ✓ Python:            http://${SERVER_IP}:3002/health"
    echo ""

    echo -e "${CYAN}🛠️  Management Commands:${NC}"
    echo -e "   cd ${INSTALL_DIR}"
    echo -e "   ./deploy.sh status       # Check service status"
    echo -e "   ./deploy.sh logs         # View logs"
    echo -e "   ./deploy.sh restart      # Restart services"
    echo -e "   ./deploy.sh stop         # Stop services"
    echo -e "   ./deploy.sh backup       # Create backup"
    echo ""

    echo -e "${CYAN}📊 Service Status:${NC}"
    cd "$INSTALL_DIR"
    docker compose -f docker-compose.production.yml ps
    echo ""

    echo -e "${CYAN}📚 Documentation:${NC}"
    echo -e "   📄 Full Guide:       ${INSTALL_DIR}/PRODUCTION_DEPLOYMENT.md"
    echo -e "   📖 Architecture:     ${INSTALL_DIR}/DEPLOYMENT_COMPLETE.md"
    echo -e "   🚀 Quick Start:      ${INSTALL_DIR}/DEPLOYMENT_SUCCESS.md"
    echo ""

    echo -e "${YELLOW}⚠️  Important Notes:${NC}"
    echo -e "   • All API keys are configured and active"
    echo -e "   • Astra DB collections are initialized with NVIDIA embeddings"
    echo -e "   • Services auto-restart on failure"
    echo -e "   • Check logs if any service shows issues: ./deploy.sh logs"
    echo ""

    echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${GREEN}  🌌 One2lvOS v1.0.2 deployed successfully! 🧲${NC}"
    echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
}

# Main installation flow
main() {
    # Get installation directory (default: ~/one2lvos)
    INSTALL_DIR="${1:-$HOME/one2lvos}"

    # Pre-flight checks
    log_step "Pre-flight Checks"
    check_docker
    check_docker_compose
    log_success "All requirements met"

    # Get installation directory
    get_install_dir "$INSTALL_DIR"

    # Execute installation steps
    clone_repo
    create_env
    deploy_services
    init_astra
    check_health
    show_access
}

# Run main installation
main "$@"
